name: discord_bot
channels:
  - defaults
dependencies:
  - python=3.11.9
  - numpy==1.26.4
  - pip
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.13
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anthropic==0.55.0
    - anyio==4.9.0
    - attrs==25.3.0
    - cachetools==5.5.2
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - colorama==0.4.6
    - discord==2.3.2
    - discord.py==2.5.2
    - distro==1.9.0
    - dotenv==0.9.9
    - filelock==3.16.1
    - fire==0.7.0
    - frozenlist==1.7.0
    - fsspec==2024.12.0
    - fugashi==1.4.0
    - google-auth==2.40.3
    - google-genai==1.23.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.27.0
    - idna==3.10
    - jaconv==0.4.0
    - Jinja2==3.1.5
    - jiter==0.10.0
    - loguru==0.7.3
    - manga-ocr==0.1.13
    - MarkupSafe==3.0.2
    - mokuro==0.2.1
    - mpmath==1.3.0
    - multidict==6.6.3
    - natsort==8.4.0
    - networkx==3.4.2
    - openai==1.93.0
    - opencv-python==4.10.0.84
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.0.0
    - propcache==0.3.2
    - protobuf==5.29.2
    - pyasn1==0.6.1
    - pyasn1_modules==0.4.2
    - pyclipper==1.3.0.post6
    - pydantic==2.11.7
    - pydantic_core==2.33.2
    - pydub==0.25.1
    - pyperclip==1.9.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.1
    - pytz==2024.2
    - PyYAML==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rsa==4.9.1
    - safetensors==0.4.5
    - scipy==1.14.1
    - shapely==2.0.6
    - six==1.17.0
    - sniffio==1.3.1
    - SpeechRecognition==3.14.3
    - sympy==1.13.1
    - tenacity==8.5.0
    - termcolor==2.5.0
    - tokenizers==0.21.0
    - torch==2.5.1
    - torchsummary==1.5.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - transformers==4.47.1
    - typing-inspection==0.4.1
    - typing_extensions==4.12.2
    - tzdata==2024.2
    - unidic-lite==1.0.8
    - urllib3==2.3.0
    - websockets==15.0.1
    - win32_setctime==1.2.0
    - yarl==1.20.1
    - yattag==1.16.1

