name: discord_bot
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
    - SpeechRecognition==3.14.3
    - pydub==0.25.1
    - discord==2.3.2
    - anthropic==0.56.0
    - dotenv==0.9.9
    - google==3.0.0
    - google-genai==1.24.0
    - openai==1.93.0
